name: Crystal CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal:1.5.0

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
